# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\Loguka\Smart_Notes\Smart_Note.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.zamitku_lw = QtWidgets.QListWidget(self.centralwidget)
        self.zamitku_lw.setGeometry(QtCore.QRect(540, 30, 256, 192))
        self.zamitku_lw.setObjectName("zamitku_lw")
        self.zamitku_te = QtWidgets.QTextEdit(self.centralwidget)
        self.zamitku_te.setGeometry(QtCore.QRect(0, 0, 531, 591))
        self.zamitku_te.setObjectName("zamitku_te")
        self.label_spusok_zam = QtWidgets.QLabel(self.centralwidget)
        self.label_spusok_zam.setGeometry(QtCore.QRect(540, 0, 251, 16))
        self.label_spusok_zam.setObjectName("label_spusok_zam")
        self.make_zam = QtWidgets.QPushButton(self.centralwidget)
        self.make_zam.setGeometry(QtCore.QRect(530, 230, 131, 23))
        self.make_zam.setObjectName("make_zam")
        self.del_zam = QtWidgets.QPushButton(self.centralwidget)
        self.del_zam.setGeometry(QtCore.QRect(660, 230, 131, 23))
        self.del_zam.setObjectName("del_zam")
        self.save_zam = QtWidgets.QPushButton(self.centralwidget)
        self.save_zam.setGeometry(QtCore.QRect(530, 260, 261, 23))
        self.save_zam.setObjectName("save_zam")
        self.label_spusok_teg_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_spusok_teg_2.setGeometry(QtCore.QRect(540, 280, 251, 16))
        self.label_spusok_teg_2.setObjectName("label_spusok_teg_2")
        self.add_teg = QtWidgets.QPushButton(self.centralwidget)
        self.add_teg.setGeometry(QtCore.QRect(530, 530, 131, 23))
        self.add_teg.setObjectName("add_teg")
        self.search_zam_teg = QtWidgets.QPushButton(self.centralwidget)
        self.search_zam_teg.setGeometry(QtCore.QRect(530, 560, 261, 23))
        self.search_zam_teg.setObjectName("search_zam_teg")
        self.tegi_lw = QtWidgets.QListWidget(self.centralwidget)
        self.tegi_lw.setGeometry(QtCore.QRect(540, 310, 256, 192))
        self.tegi_lw.setObjectName("tegi_lw")
        self.del_teg = QtWidgets.QPushButton(self.centralwidget)
        self.del_teg.setGeometry(QtCore.QRect(660, 530, 131, 23))
        self.del_teg.setObjectName("del_teg")
        self.tegi_le = QtWidgets.QLineEdit(self.centralwidget)
        self.tegi_le.setGeometry(QtCore.QRect(540, 510, 251, 20))
        self.tegi_le.setObjectName("tegi_le")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_spusok_zam.setText(_translate("MainWindow", "Spusok Zamitok"))
        self.make_zam.setText(_translate("MainWindow", "Stovorutu Zamitku"))
        self.del_zam.setText(_translate("MainWindow", "Vudalutu Zamitku"))
        self.save_zam.setText(_translate("MainWindow", "Sochranutu Zamitku"))
        self.label_spusok_teg_2.setText(_translate("MainWindow", "Spusok Tegiw"))
        self.add_teg.setText(_translate("MainWindow", "Dodatu do zamitku"))
        self.search_zam_teg.setText(_translate("MainWindow", "Prosto Knopka"))
        self.del_teg.setText(_translate("MainWindow", "Vidkriputu vid zamitku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
